"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetAssistant404Response = instanceOfGetAssistant404Response;
exports.GetAssistant404ResponseFromJSON = GetAssistant404ResponseFromJSON;
exports.GetAssistant404ResponseFromJSONTyped = GetAssistant404ResponseFromJSONTyped;
exports.GetAssistant404ResponseToJSON = GetAssistant404ResponseToJSON;
exports.GetAssistant404ResponseToJSONTyped = GetAssistant404ResponseToJSONTyped;
/**
 * Check if a given object implements the GetAssistant404Response interface.
 */
function instanceOfGetAssistant404Response(value) {
    return true;
}
function GetAssistant404ResponseFromJSON(json) {
    return GetAssistant404ResponseFromJSONTyped(json, false);
}
function GetAssistant404ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        message: json["message"] == null ? undefined : json["message"],
    };
}
function GetAssistant404ResponseToJSON(json) {
    return GetAssistant404ResponseToJSONTyped(json, false);
}
function GetAssistant404ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        message: value["message"],
    };
}
