"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetAssistant200Response = instanceOfGetAssistant200Response;
exports.GetAssistant200ResponseFromJSON = GetAssistant200ResponseFromJSON;
exports.GetAssistant200ResponseFromJSONTyped = GetAssistant200ResponseFromJSONTyped;
exports.GetAssistant200ResponseToJSON = GetAssistant200ResponseToJSON;
exports.GetAssistant200ResponseToJSONTyped = GetAssistant200ResponseToJSONTyped;
var ListAssistants200ResponseInnerConfigResult_1 = require("./ListAssistants200ResponseInnerConfigResult");
/**
 * Check if a given object implements the GetAssistant200Response interface.
 */
function instanceOfGetAssistant200Response(value) {
    if (!("configResult" in value) || value["configResult"] === undefined)
        return false;
    if (!("ownerSlug" in value) || value["ownerSlug"] === undefined)
        return false;
    if (!("packageSlug" in value) || value["packageSlug"] === undefined)
        return false;
    return true;
}
function GetAssistant200ResponseFromJSON(json) {
    return GetAssistant200ResponseFromJSONTyped(json, false);
}
function GetAssistant200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        configResult: (0, ListAssistants200ResponseInnerConfigResult_1.ListAssistants200ResponseInnerConfigResultFromJSON)(json["configResult"]),
        ownerSlug: json["ownerSlug"],
        packageSlug: json["packageSlug"],
        iconUrl: json["iconUrl"] == null ? undefined : json["iconUrl"],
        onPremProxyUrl: json["onPremProxyUrl"] == null ? undefined : json["onPremProxyUrl"],
        useOnPremProxy: json["useOnPremProxy"] == null ? undefined : json["useOnPremProxy"],
        rawYaml: json["rawYaml"] == null ? undefined : json["rawYaml"],
    };
}
function GetAssistant200ResponseToJSON(json) {
    return GetAssistant200ResponseToJSONTyped(json, false);
}
function GetAssistant200ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        configResult: (0, ListAssistants200ResponseInnerConfigResult_1.ListAssistants200ResponseInnerConfigResultToJSON)(value["configResult"]),
        ownerSlug: value["ownerSlug"],
        packageSlug: value["packageSlug"],
        iconUrl: value["iconUrl"],
        onPremProxyUrl: value["onPremProxyUrl"],
        useOnPremProxy: value["useOnPremProxy"],
        rawYaml: value["rawYaml"],
    };
}
