"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetAssistant403Response = instanceOfGetAssistant403Response;
exports.GetAssistant403ResponseFromJSON = GetAssistant403ResponseFromJSON;
exports.GetAssistant403ResponseFromJSONTyped = GetAssistant403ResponseFromJSONTyped;
exports.GetAssistant403ResponseToJSON = GetAssistant403ResponseToJSON;
exports.GetAssistant403ResponseToJSONTyped = GetAssistant403ResponseToJSONTyped;
/**
 * Check if a given object implements the GetAssistant403Response interface.
 */
function instanceOfGetAssistant403Response(value) {
    return true;
}
function GetAssistant403ResponseFromJSON(json) {
    return GetAssistant403ResponseFromJSONTyped(json, false);
}
function GetAssistant403ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        message: json["message"] == null ? undefined : json["message"],
    };
}
function GetAssistant403ResponseToJSON(json) {
    return GetAssistant403ResponseToJSONTyped(json, false);
}
function GetAssistant403ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        message: value["message"],
    };
}
