"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetFreeTrialStatus200Response = instanceOfGetFreeTrialStatus200Response;
exports.GetFreeTrialStatus200ResponseFromJSON = GetFreeTrialStatus200ResponseFromJSON;
exports.GetFreeTrialStatus200ResponseFromJSONTyped = GetFreeTrialStatus200ResponseFromJSONTyped;
exports.GetFreeTrialStatus200ResponseToJSON = GetFreeTrialStatus200ResponseToJSON;
exports.GetFreeTrialStatus200ResponseToJSONTyped = GetFreeTrialStatus200ResponseToJSONTyped;
/**
 * Check if a given object implements the GetFreeTrialStatus200Response interface.
 */
function instanceOfGetFreeTrialStatus200Response(value) {
    if (!("optedInToFreeTrial" in value) ||
        value["optedInToFreeTrial"] === undefined)
        return false;
    if (!("chatLimit" in value) || value["chatLimit"] === undefined)
        return false;
    if (!("autocompleteLimit" in value) ||
        value["autocompleteLimit"] === undefined)
        return false;
    return true;
}
function GetFreeTrialStatus200ResponseFromJSON(json) {
    return GetFreeTrialStatus200ResponseFromJSONTyped(json, false);
}
function GetFreeTrialStatus200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        optedInToFreeTrial: json["optedInToFreeTrial"],
        chatCount: json["chatCount"] == null ? undefined : json["chatCount"],
        autocompleteCount: json["autocompleteCount"] == null ? undefined : json["autocompleteCount"],
        chatLimit: json["chatLimit"],
        autocompleteLimit: json["autocompleteLimit"],
    };
}
function GetFreeTrialStatus200ResponseToJSON(json) {
    return GetFreeTrialStatus200ResponseToJSONTyped(json, false);
}
function GetFreeTrialStatus200ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        optedInToFreeTrial: value["optedInToFreeTrial"],
        chatCount: value["chatCount"],
        autocompleteCount: value["autocompleteCount"],
        chatLimit: value["chatLimit"],
        autocompleteLimit: value["autocompleteLimit"],
    };
}
