"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetModelsAddOnCheckoutUrl200Response = instanceOfGetModelsAddOnCheckoutUrl200Response;
exports.GetModelsAddOnCheckoutUrl200ResponseFromJSON = GetModelsAddOnCheckoutUrl200ResponseFromJSON;
exports.GetModelsAddOnCheckoutUrl200ResponseFromJSONTyped = GetModelsAddOnCheckoutUrl200ResponseFromJSONTyped;
exports.GetModelsAddOnCheckoutUrl200ResponseToJSON = GetModelsAddOnCheckoutUrl200ResponseToJSON;
exports.GetModelsAddOnCheckoutUrl200ResponseToJSONTyped = GetModelsAddOnCheckoutUrl200ResponseToJSONTyped;
/**
 * Check if a given object implements the GetModelsAddOnCheckoutUrl200Response interface.
 */
function instanceOfGetModelsAddOnCheckoutUrl200Response(value) {
    if (!("url" in value) || value["url"] === undefined)
        return false;
    return true;
}
function GetModelsAddOnCheckoutUrl200ResponseFromJSON(json) {
    return GetModelsAddOnCheckoutUrl200ResponseFromJSONTyped(json, false);
}
function GetModelsAddOnCheckoutUrl200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        url: json["url"],
    };
}
function GetModelsAddOnCheckoutUrl200ResponseToJSON(json) {
    return GetModelsAddOnCheckoutUrl200ResponseToJSONTyped(json, false);
}
function GetModelsAddOnCheckoutUrl200ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        url: value["url"],
    };
}
