"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetModelsAddOnCheckoutUrl500Response = instanceOfGetModelsAddOnCheckoutUrl500Response;
exports.GetModelsAddOnCheckoutUrl500ResponseFromJSON = GetModelsAddOnCheckoutUrl500ResponseFromJSON;
exports.GetModelsAddOnCheckoutUrl500ResponseFromJSONTyped = GetModelsAddOnCheckoutUrl500ResponseFromJSONTyped;
exports.GetModelsAddOnCheckoutUrl500ResponseToJSON = GetModelsAddOnCheckoutUrl500ResponseToJSON;
exports.GetModelsAddOnCheckoutUrl500ResponseToJSONTyped = GetModelsAddOnCheckoutUrl500ResponseToJSONTyped;
/**
 * Check if a given object implements the GetModelsAddOnCheckoutUrl500Response interface.
 */
function instanceOfGetModelsAddOnCheckoutUrl500Response(value) {
    return true;
}
function GetModelsAddOnCheckoutUrl500ResponseFromJSON(json) {
    return GetModelsAddOnCheckoutUrl500ResponseFromJSONTyped(json, false);
}
function GetModelsAddOnCheckoutUrl500ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        message: json["message"] == null ? undefined : json["message"],
    };
}
function GetModelsAddOnCheckoutUrl500ResponseToJSON(json) {
    return GetModelsAddOnCheckoutUrl500ResponseToJSONTyped(json, false);
}
function GetModelsAddOnCheckoutUrl500ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        message: value["message"],
    };
}
