"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetPolicy200Response = instanceOfGetPolicy200Response;
exports.GetPolicy200ResponseFromJSON = GetPolicy200ResponseFromJSON;
exports.GetPolicy200ResponseFromJSONTyped = GetPolicy200ResponseFromJSONTyped;
exports.GetPolicy200ResponseToJSON = GetPolicy200ResponseToJSON;
exports.GetPolicy200ResponseToJSONTyped = GetPolicy200ResponseToJSONTyped;
/**
 * Check if a given object implements the GetPolicy200Response interface.
 */
function instanceOfGetPolicy200Response(value) {
    return true;
}
function GetPolicy200ResponseFromJSON(json) {
    return GetPolicy200ResponseFromJSONTyped(json, false);
}
function GetPolicy200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        policy: json["policy"] == null ? undefined : json["policy"],
        orgSlug: json["orgSlug"] == null ? undefined : json["orgSlug"],
    };
}
function GetPolicy200ResponseToJSON(json) {
    return GetPolicy200ResponseToJSONTyped(json, false);
}
function GetPolicy200ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        policy: value["policy"],
        orgSlug: value["orgSlug"],
    };
}
