"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListAssistants200ResponseInner = instanceOfListAssistants200ResponseInner;
exports.ListAssistants200ResponseInnerFromJSON = ListAssistants200ResponseInnerFromJSON;
exports.ListAssistants200ResponseInnerFromJSONTyped = ListAssistants200ResponseInnerFromJSONTyped;
exports.ListAssistants200ResponseInnerToJSON = ListAssistants200ResponseInnerToJSON;
exports.ListAssistants200ResponseInnerToJSONTyped = ListAssistants200ResponseInnerToJSONTyped;
var ListAssistants200ResponseInnerConfigResult_1 = require("./ListAssistants200ResponseInnerConfigResult");
/**
 * Check if a given object implements the ListAssistants200ResponseInner interface.
 */
function instanceOfListAssistants200ResponseInner(value) {
    if (!("configResult" in value) || value["configResult"] === undefined)
        return false;
    if (!("ownerSlug" in value) || value["ownerSlug"] === undefined)
        return false;
    if (!("packageSlug" in value) || value["packageSlug"] === undefined)
        return false;
    return true;
}
function ListAssistants200ResponseInnerFromJSON(json) {
    return ListAssistants200ResponseInnerFromJSONTyped(json, false);
}
function ListAssistants200ResponseInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        configResult: (0, ListAssistants200ResponseInnerConfigResult_1.ListAssistants200ResponseInnerConfigResultFromJSON)(json["configResult"]),
        ownerSlug: json["ownerSlug"],
        packageSlug: json["packageSlug"],
        iconUrl: json["iconUrl"] == null ? undefined : json["iconUrl"],
        onPremProxyUrl: json["onPremProxyUrl"] == null ? undefined : json["onPremProxyUrl"],
        useOnPremProxy: json["useOnPremProxy"] == null ? undefined : json["useOnPremProxy"],
        rawYaml: json["rawYaml"] == null ? undefined : json["rawYaml"],
    };
}
function ListAssistants200ResponseInnerToJSON(json) {
    return ListAssistants200ResponseInnerToJSONTyped(json, false);
}
function ListAssistants200ResponseInnerToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        configResult: (0, ListAssistants200ResponseInnerConfigResult_1.ListAssistants200ResponseInnerConfigResultToJSON)(value["configResult"]),
        ownerSlug: value["ownerSlug"],
        packageSlug: value["packageSlug"],
        iconUrl: value["iconUrl"],
        onPremProxyUrl: value["onPremProxyUrl"],
        useOnPremProxy: value["useOnPremProxy"],
        rawYaml: value["rawYaml"],
    };
}
