"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListAssistants404Response = instanceOfListAssistants404Response;
exports.ListAssistants404ResponseFromJSON = ListAssistants404ResponseFromJSON;
exports.ListAssistants404ResponseFromJSONTyped = ListAssistants404ResponseFromJSONTyped;
exports.ListAssistants404ResponseToJSON = ListAssistants404ResponseToJSON;
exports.ListAssistants404ResponseToJSONTyped = ListAssistants404ResponseToJSONTyped;
/**
 * Check if a given object implements the ListAssistants404Response interface.
 */
function instanceOfListAssistants404Response(value) {
    return true;
}
function ListAssistants404ResponseFromJSON(json) {
    return ListAssistants404ResponseFromJSONTyped(json, false);
}
function ListAssistants404ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        message: json["message"] == null ? undefined : json["message"],
    };
}
function ListAssistants404ResponseToJSON(json) {
    return ListAssistants404ResponseToJSONTyped(json, false);
}
function ListAssistants404ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        message: value["message"],
    };
}
