"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListAssistantFullSlugs429Response = instanceOfListAssistantFullSlugs429Response;
exports.ListAssistantFullSlugs429ResponseFromJSON = ListAssistantFullSlugs429ResponseFromJSON;
exports.ListAssistantFullSlugs429ResponseFromJSONTyped = ListAssistantFullSlugs429ResponseFromJSONTyped;
exports.ListAssistantFullSlugs429ResponseToJSON = ListAssistantFullSlugs429ResponseToJSON;
exports.ListAssistantFullSlugs429ResponseToJSONTyped = ListAssistantFullSlugs429ResponseToJSONTyped;
/**
 * Check if a given object implements the ListAssistantFullSlugs429Response interface.
 */
function instanceOfListAssistantFullSlugs429Response(value) {
    return true;
}
function ListAssistantFullSlugs429ResponseFromJSON(json) {
    return ListAssistantFullSlugs429ResponseFromJSONTyped(json, false);
}
function ListAssistantFullSlugs429ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        message: json["message"] == null ? undefined : json["message"],
    };
}
function ListAssistantFullSlugs429ResponseToJSON(json) {
    return ListAssistantFullSlugs429ResponseToJSONTyped(json, false);
}
function ListAssistantFullSlugs429ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        message: value["message"],
    };
}
