"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListOrganizations200Response = instanceOfListOrganizations200Response;
exports.ListOrganizations200ResponseFromJSON = ListOrganizations200ResponseFromJSON;
exports.ListOrganizations200ResponseFromJSONTyped = ListOrganizations200ResponseFromJSONTyped;
exports.ListOrganizations200ResponseToJSON = ListOrganizations200ResponseToJSON;
exports.ListOrganizations200ResponseToJSONTyped = ListOrganizations200ResponseToJSONTyped;
var ListOrganizations200ResponseOrganizationsInner_1 = require("./ListOrganizations200ResponseOrganizationsInner");
/**
 * Check if a given object implements the ListOrganizations200Response interface.
 */
function instanceOfListOrganizations200Response(value) {
    if (!("organizations" in value) || value["organizations"] === undefined)
        return false;
    return true;
}
function ListOrganizations200ResponseFromJSON(json) {
    return ListOrganizations200ResponseFromJSONTyped(json, false);
}
function ListOrganizations200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        organizations: json["organizations"].map(ListOrganizations200ResponseOrganizationsInner_1.ListOrganizations200ResponseOrganizationsInnerFromJSON),
    };
}
function ListOrganizations200ResponseToJSON(json) {
    return ListOrganizations200ResponseToJSONTyped(json, false);
}
function ListOrganizations200ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        organizations: value["organizations"].map(ListOrganizations200ResponseOrganizationsInner_1.ListOrganizations200ResponseOrganizationsInnerToJSON),
    };
}
