"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListAssistants200ResponseInnerConfigResult = instanceOfListAssistants200ResponseInnerConfigResult;
exports.ListAssistants200ResponseInnerConfigResultFromJSON = ListAssistants200ResponseInnerConfigResultFromJSON;
exports.ListAssistants200ResponseInnerConfigResultFromJSONTyped = ListAssistants200ResponseInnerConfigResultFromJSONTyped;
exports.ListAssistants200ResponseInnerConfigResultToJSON = ListAssistants200ResponseInnerConfigResultToJSON;
exports.ListAssistants200ResponseInnerConfigResultToJSONTyped = ListAssistants200ResponseInnerConfigResultToJSONTyped;
/**
 * Check if a given object implements the ListAssistants200ResponseInnerConfigResult interface.
 */
function instanceOfListAssistants200ResponseInnerConfigResult(value) {
    if (!("config" in value) || value["config"] === undefined)
        return false;
    if (!("configLoadInterrupted" in value) ||
        value["configLoadInterrupted"] === undefined)
        return false;
    return true;
}
function ListAssistants200ResponseInnerConfigResultFromJSON(json) {
    return ListAssistants200ResponseInnerConfigResultFromJSONTyped(json, false);
}
function ListAssistants200ResponseInnerConfigResultFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        config: json["config"],
        configLoadInterrupted: json["configLoadInterrupted"],
        errors: json["errors"] == null ? undefined : json["errors"],
    };
}
function ListAssistants200ResponseInnerConfigResultToJSON(json) {
    return ListAssistants200ResponseInnerConfigResultToJSONTyped(json, false);
}
function ListAssistants200ResponseInnerConfigResultToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        config: value["config"],
        configLoadInterrupted: value["configLoadInterrupted"],
        errors: value["errors"],
    };
}
