"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListAssistants401Response = instanceOfListAssistants401Response;
exports.ListAssistants401ResponseFromJSON = ListAssistants401ResponseFromJSON;
exports.ListAssistants401ResponseFromJSONTyped = ListAssistants401ResponseFromJSONTyped;
exports.ListAssistants401ResponseToJSON = ListAssistants401ResponseToJSON;
exports.ListAssistants401ResponseToJSONTyped = ListAssistants401ResponseToJSONTyped;
/**
 * Check if a given object implements the ListAssistants401Response interface.
 */
function instanceOfListAssistants401Response(value) {
    return true;
}
function ListAssistants401ResponseFromJSON(json) {
    return ListAssistants401ResponseFromJSONTyped(json, false);
}
function ListAssistants401ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        message: json["message"] == null ? undefined : json["message"],
    };
}
function ListAssistants401ResponseToJSON(json) {
    return ListAssistants401ResponseToJSONTyped(json, false);
}
function ListAssistants401ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        message: value["message"],
    };
}
