"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfListOrganizations200ResponseOrganizationsInner = instanceOfListOrganizations200ResponseOrganizationsInner;
exports.ListOrganizations200ResponseOrganizationsInnerFromJSON = ListOrganizations200ResponseOrganizationsInnerFromJSON;
exports.ListOrganizations200ResponseOrganizationsInnerFromJSONTyped = ListOrganizations200ResponseOrganizationsInnerFromJSONTyped;
exports.ListOrganizations200ResponseOrganizationsInnerToJSON = ListOrganizations200ResponseOrganizationsInnerToJSON;
exports.ListOrganizations200ResponseOrganizationsInnerToJSONTyped = ListOrganizations200ResponseOrganizationsInnerToJSONTyped;
/**
 * Check if a given object implements the ListOrganizations200ResponseOrganizationsInner interface.
 */
function instanceOfListOrganizations200ResponseOrganizationsInner(value) {
    if (!("id" in value) || value["id"] === undefined)
        return false;
    if (!("name" in value) || value["name"] === undefined)
        return false;
    if (!("slug" in value) || value["slug"] === undefined)
        return false;
    return true;
}
function ListOrganizations200ResponseOrganizationsInnerFromJSON(json) {
    return ListOrganizations200ResponseOrganizationsInnerFromJSONTyped(json, false);
}
function ListOrganizations200ResponseOrganizationsInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        name: json["name"],
        iconUrl: json["iconUrl"] == null ? undefined : json["iconUrl"],
        slug: json["slug"],
    };
}
function ListOrganizations200ResponseOrganizationsInnerToJSON(json) {
    return ListOrganizations200ResponseOrganizationsInnerToJSONTyped(json, false);
}
function ListOrganizations200ResponseOrganizationsInnerToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        id: value["id"],
        name: value["name"],
        iconUrl: value["iconUrl"],
        slug: value["slug"],
    };
}
