"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSyncSecretsRequest = instanceOfSyncSecretsRequest;
exports.SyncSecretsRequestFromJSON = SyncSecretsRequestFromJSON;
exports.SyncSecretsRequestFromJSONTyped = SyncSecretsRequestFromJSONTyped;
exports.SyncSecretsRequestToJSON = SyncSecretsRequestToJSON;
exports.SyncSecretsRequestToJSONTyped = SyncSecretsRequestToJSONTyped;
/**
 * Check if a given object implements the SyncSecretsRequest interface.
 */
function instanceOfSyncSecretsRequest(value) {
    if (!("fqsns" in value) || value["fqsns"] === undefined)
        return false;
    return true;
}
function SyncSecretsRequestFromJSON(json) {
    return SyncSecretsRequestFromJSONTyped(json, false);
}
function SyncSecretsRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        fqsns: json["fqsns"],
        orgScopeId: json["orgScopeId"] == null ? undefined : json["orgScopeId"],
        orgScopeSlug: json["orgScopeSlug"] == null ? undefined : json["orgScopeSlug"],
    };
}
function SyncSecretsRequestToJSON(json) {
    return SyncSecretsRequestToJSONTyped(json, false);
}
function SyncSecretsRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        fqsns: value["fqsns"],
        orgScopeId: value["orgScopeId"],
        orgScopeSlug: value["orgScopeSlug"],
    };
}
